version: "3.9"

services:
  client-app:
    build:
      context: ../../
      dockerfile: apps/client-app/Dockerfile
    ports:
      - "3001:3001"
    restart: always
  monitor-app:
    build:
      context: ../../
      dockerfile: apps/monitor-app/Dockerfile
    ports:
      - "3000:3000"
    restart: always
