version: "3.9"

services:
  client-app:
    build:
      context: ../../
      dockerfile: docker/client-app.Dockerfile
    ports:
      - "3001:3001"
    restart: always
  monitor-app:
    build:
      context: ../../
      dockerfile: docker/monitor/dockerfiles/monitor-app.prod.Dockerfile
    ports:
      - "3000:3000"
    restart: always
