name: Check application build
on:
  pull_request:
    branches: [main]
    paths:
      - "apps/monitor-app/**"
      - "apps/client-app/**"
      - "packages/client-sdk/**"

permissions:
  contents: read
jobs:
  check_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify commits behind
        run: |
          git fetch
          COMMITS_BEHIND=$(git rev-list --left-only --count origin/$GITHUB_BASE_REF...origin/$GITHUB_HEAD_REF)
          if [ $COMMITS_BEHIND -gt 0 ]; then echo "source branch is $COMMITS_BEHIND commit(s) behind target branch" && exit 1; fi

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install deps
        run: pnpm install

      - name: Determine changed parts
        id: changes
        run: |
          git fetch origin $GITHUB_BASE_REF --depth=1

          MERGE_BASE=$(git merge-base origin/$GITHUB_BASE_REF HEAD || echo "")

          if [ -z "$MERGE_BASE" ]; then
            CHANGED_FILES=$(git diff --name-only HEAD)
          else
            CHANGED_FILES=$(git diff --name-only $MERGE_BASE HEAD)
          fi


          echo "sdk_changed=false" >> $GITHUB_OUTPUT
          echo "monitor_changed=false" >> $GITHUB_OUTPUT
          echo "client_changed=false" >> $GITHUB_OUTPUT

          if echo "$CHANGED_FILES" | grep -q "^packages/client-sdk/"; then
            echo "sdk_changed=true" >> $GITHUB_OUTPUT
          fi

          if echo "$CHANGED_FILES" | grep -q "^apps/monitor-app/"; then
            echo "monitor_changed=true" >> $GITHUB_OUTPUT
          fi

          if echo "$CHANGED_FILES" | grep -q "^apps/client-app/"; then
            echo "client_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Check sdk
        if: steps.changes.outputs.sdk_changed == 'true'
        run: pnpm --filter cwv-monitor-sdk build

      - name: Check monitor
        if: steps.changes.outputs.monitor_changed == 'true'
        run: SKIP_VALIDATION=true pnpm --filter cwv-monitor-app build

        # SDK can destroy client build, so let's verify it here too
      - name: Check demo
        if: steps.changes.outputs.client_changed == 'true' || steps.changes.outputs.sdk_changed == 'true'
        run: SKIP_VALIDATION=true pnpm --filter cwv-monitor-client build
